### ISSUE TITLE
Finetuning Script

### ISSUE THREAD

**Issue by hassantsyed** [FreedomIntelligence/BlenderLLM#1]
Thank you for this, it's very impressive.

I am very interested in if there is an accompanying paper of the methodology used for finetuning, the finetuning scripts, and the hyperparameters?

**Comment by KurtDu** [comment]
We have released our [technical report](https://www.arxiv.org/abs/2412.14203), which includes details of our training process. Please feel free to refer to it. Additionally, you can use the repository at [LLaMA-Factory](https://github.com/hiyouga/LLaMA-Factory) to fine-tune the model. Simply adjust our dataset, [BlendNet](https://huggingface.co/datasets/FreedomIntelligence/BlendNet), to match the provided template.

**Comment by hassantsyed** [comment]
Thank you!
